### PR TITLE
Add local copy of the key

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to
- https://gsa-tts.slack.com/archives/C04LR4FBM2N/p1680014076410119
- https://github.com/cloudfoundry/cli/issues/2390
- https://github.com/GSA/data.gov/issues/4265

Changes:
- add the key locally so that we don't need to query for the key at every runtime.  Yes, the key could change, but this is a short term solution to keep operations going while the longer-term solution is still in the works

### CODE REVIEW

**Comment by mogul** [comment]
@nickumia-reisys do you want to retarget this PR to the upstream repo at `cloud-gov/cg-cli-tools` and get it merged so we can remove this fork?

**Comment by nickumia-reisys** [comment]
This was meant to be a temporary solution.  Do you feel like this is a necessary design choice?  @mogul

**Comment by mogul** [comment]
I don't, no... It would get around upstream problems with the key in future but would then leave us on the hook for maintaining an up-to-date key here in the codebase. That seems like a bad trade-off for something that should rarely occur!

**Comment by nickumia-reisys** [comment]
Hmm.. it seems like we were already off of this fork.  So this can be safely closed.

**Comment by mogul** [comment]
Can we delete/archive the fork now too?

**Comment by nickumia-reisys** [comment]
I believe so.  I know of no reasons to keep this fork around.

**Comment by mogul** [comment]
I don't have the perms to archive it... Do you?

**Pull request closed without merging**
